FROM nginx:latest

# Add our nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# FROM ubuntu:16.04

# RUN apt-get update \
#  && apt-get install -y \
#     wget \
#     net-tools \
#     nginx

# # # Delete the default configuration
# # RUN rm -v /etc/nginx/nginx.conf

# # Add our nginx configuration
# COPY nginx.conf /etc/nginx/nginx.conf

# CMD ["service", "nginx", "start"]
